version: "3.8"

services:
  pixelscoutdb:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pixelscoutdb:/var/lib/postgresql/data

volumes:
  pixelscoutdb:
